### PR TITLE
Added person analytics tracking to wistia embeds + new wistia button shortcode

### PR DESCRIPTION
**Pull request by briankalwat**
## DESCRIPTION

This PR wires up the [logging of analytics to wistia that include person/content item/entity data](https://github.com/NewSpring/Rock/pull/1071/files#diff-c4f6221dc3c8f4b1cfe77c4b20f6b8b3R32) that gets re-linked back to Rock interactions when the wistia sync job runs.

It also adds a new lava shortcode that implements a button that launches a modal with a wistia video embedded in it.

### How do I test this PR?

1. Pull this branch down.
2. Create new `wistiaButton` shortcode in your environment's database - you can copy the lava/parameters defined here: https://brian-rock.newspring.cc/page/1176?lavaShortcodeId=98
3. Check the video embeds/buttons following pages/blocks:
- Sermon Detail Page Video Embed
- Editorial Detail Page Video Button (/stories)
- Page Builder Blocks (you'll need to add a video to these - Hero, Ad Unit, Side By Side)
- Network Music Resource Tutorial Videos: https://brian-new.newspringnetwork.com/resources/music/able

## TODO

- [X] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [X] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [X] Testing info includes any items that need to be added to a local Rock instance in order to test and/or the database against which it can be tested.
- [ ] Upload GIF(s) of relevant changes
- [X] Set a relevant reviewer

## REVIEW

- [ ] Review code through the lens of being concise, simple, and well-documented
- [ ] Manual QA to ensure the changes look/behave as expected

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@briankalwat Some interesting behavior differences between the modals I see when I put a video on the hero versus the ad-unit. The hero modal is big and automatically starts whereas the ad-unit modal is tiny, has a white background with a close button on it, and doesn't auto start. Any reason for the differences? Is it just my instance that's set up incorrectly? I would think that the modals should be the same.

Also, when I put the video in the ad-unit the first time I click the button I get the full video:

Screenshot 2020-04-05 09 25 06

But after I refresh the page, the modal doesn't seem to want to load all the way:

Screenshot 2020-04-05 09 24 30

Any thoughts on that?

**Comment by richarddubay** [comment]
Okay, I guess don't worry about the second part of that question. It seems to be working fine now. 🤷‍♂️

**Comment by briankalwat** [comment]
@richarddubay what you're seeing in the hero is because it isn't using the new shortcode. If you see a large modal, it either means that:
1. The wistia popover code is hardcoded into the lava field of that content component block.
2. The hero lava shortcode is hardcoded on your database and not pointing at it's template correctly.

As far as the modal not loading, I just looked at `rich.newspring.cc` and i'm unable to reproduce that.

**Comment by richarddubay** [comment]
So the tiny modal should be what people see?

**Comment by briankalwat** [comment]
@richarddubay unfortunately for now, yes. Bootstrap has a modal size modifer, `modal-lg`, but it is currently overridden by some changes Spark has made to core CSS. I've mentioned it to Garrett, and he said he would look into it.

**Comment by richarddubay** [comment]
Okay. I'm not sure what the purpose of the modal is. Personal opinion is that it looked better without the modal. The big window just feels better to me. But if this is what we want then it looks like it's working. :shipit:

**Pull request merged**
