### PR TITLE
added service note attribute value to service times data shortcode

### PR DESCRIPTION
**Pull request by briankalwat**
## DESCRIPTION

This PR adds the ability to add a text note for a specific service in the service times matrix for campuses. This is useful for details that pertain to a specific campus/service.

### How do I test this PR?

- Go to General Settings > Campuses, and edit a campus.
- Scroll down to the "Service Times" matrix attribute. Click on/add a row, and add a value in the "Service Note" attribute field.
- The note you added should be visible on the locations swiper on one of the following pages, depending on the type of service that you added the note to.

https://newspring.cc/locations
https://newspring.cc/fuse/locations

- "Get Directions" button should only be visible if there is a value in the directions attribute that corresponds with the service's type.

## TODO

- [X] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [X] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [X] Testing info includes any items that need to be added to a local Rock instance in order to test and/or the database against which it can be tested.
- [ ] Upload GIF(s) of relevant changes
- [X] Set a relevant reviewer

## REVIEW

- [ ] Review code through the lens of being concise, simple, and well-documented
- [ ] Manual QA to ensure the changes look/behave as expected

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@briankalwat So this looks like it works. One thing I see is that it doesn't handle single quotes. Is this expected?

Screen Shot 2020-09-29 at 4 05 38 PM
Screen Shot 2020-09-29 at 4 05 48 PM

**Comment by briankalwat** [comment]
@richarddubay nope. The stupid quotes/apostrophe bug strikes again.

**Comment by briankalwat** [comment]
@richarddubay okay, should be fixed with that last commit. Thanks for catching that!

**Comment by richarddubay** [comment]
Yep, much better.

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
