### PR TITLE
Feature optimize my workflow

### PR DESCRIPTION
**Pull request by benwiley**
- Change to OnLoad instead of OnInit so the query happens later in the page loading cycle
- Don't requery on postbacks
- Use one query instead of two so that linq can optimize itself

ROCK-932

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@benwiley nice! Any way to get a benchmark prior to merging so we can see the impact?

**Comment by dcs619** [comment]
@jbaxleyiii we knew it was inefficient based on this 
ghofyq120sxtvezgxllofb72dcjsch-cpirwbxhufhk

The first 3 curves are switching themes, the last curve is without this block.  I don't think we have a benchmark since the optimization.

**Comment by jbaxleyiii** [comment]
@dcs619 NICE! the new one is deployed to alpha. Can we check the status with alpha?

**Comment by dcs619** [comment]
@jbaxleyiii alpha doesn't seem a lot faster but I don't have newrelic to tell me what's running.... there seems to be a good bit we could optimize in the theme

**Comment by jbaxleyiii** [comment]
@dcs619 have we tried switching to the stock theme and seeing the speed changes?

**Pull request merged**
