### PR TITLE
Fixes iOS universal links

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

App links don't consistently open on everyone's app. This fixes that.

### How do I test this PR?

Boot up your instance and then go to content served from your site.

## TODO

- [ ] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Testing info includes any items that need to be added to a local Rock instance in order to test and/or the database against which it can be tested.
- [ ] Upload GIF(s) of relevant changes
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review code through the lens of being concise, simple, and well-documented
- [ ] Manual QA to ensure the changes look/behave as expected

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
Did you do anything else besides make this change? Add your URL as an `applink` in Xcode or anything? I can't paste a URL in the sim to test and I tried running `xcrun simctl openurl booted https://rich.newspring.cc/devotionals/colossians-a-28-day-bible-study/gratitude-adjustment` but it just opens a link to my site in Safari.

**Comment by redreceipt** [comment]
oh yea, you have to add the URL as an applink, sorry

**Comment by richarddubay** [comment]
> oh yea, you have to add the URL as an applink, sorry

Yeah, I did that too. Hmmm...

**Comment by richarddubay** [comment]
@redreceipt I made a change here to fix the association file. Do you want to go ahead and test it before I approve it?

**Pull request merged**
