### PR TITLE
Added changes to giving history lava template to give access to business transactions

### PR DESCRIPTION
**Pull request by briankalwat**
### What does this PR do, or why is it needed?
This PR introduces changes to our giving history lava template that enables users to see transactions related to their businesses, which are separate from personal transactions.

### How do I test this PR?
- Clone this branch
- Point connectionstrings to `brian`
- Impersonate `/Person/19308` (or any other person with a business attached to them)
- View giving history at `/give/history`
- In the "Filters" accordion, buttons for personal/business transactions should be visible and allow you to change which transactions you're viewing.

image

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Testing info includes any items that need to be added to a local Rock instance in order to test and/or the database against which it can be tested.
- [x] Upload GIF(s) of relevant changes
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review code through the lens of being concise, simple, and well-documented
- [ ] Manual QA to ensure the changes look/behave as expected

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@briankalwat Did you mean to remove the yearly contribution buttons entirely? Or was it only supposed to be for the businesses?
Screen Shot 2020-10-20 at 1 57 05 PM

**Comment by briankalwat** [comment]
> @briankalwat Did you mean to remove the yearly contribution buttons entirely? Or was it only supposed to be for the businesses?
> 
> Screen Shot 2020-10-20 at 1 57 05 PM

@richarddubay they should be visible when viewing personal contributions. That screenshot isn't the whole page.

**Comment by richarddubay** [comment]
Nope, it's not the whole page, but the buttons should be to the right of the filters and they didn't show up in my testing. But maybe I just did something wrong.

**Comment by briankalwat** [comment]
@richarddubay should be working now.

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
