### PR TITLE
Updated feed template to not reference/use scriptures/communicators shortcodes to try to cut down on database calls

### PR DESCRIPTION
**Pull request by briankalwat**
## DESCRIPTION

This PR improves the performance of our RSS feeds by trying to reduce the number of queries we make to the database. The shortcodes we were using for getting communicator/scripture matrix values via SQL were not performant, so I've attempted to return the values in a usable format directly from the attribute value in lava by updating the attribute matrix template output format for these two attributes.

## TESTING
To test the feed changes, you can visit the following links. I've already made the necessary changes to the alpha database to enable the changes to take effect.

### Sermon Audio
Specifically Check Communicator Names
Current: https://newspring.cc/GetChannelFeed.ashx?Count=100&ChannelId=19&TemplateId=1058
Updated: https://brian-new.newspring.cc/GetChannelFeed.ashx?Count=100&ChannelId=19&TemplateId=1058

### Devotionals
Specifically Check Scripture References
Current: https://newspring.cc/GetChannelFeed.ashx?Count=100&ChannelId=17&TemplateId=523
Updated: https://brian-new.newspring.cc/GetChannelFeed.ashx?Count=100&ChannelId=17&TemplateId=523

## TODO

- [X] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [X] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [X] Testing info includes any items that need to be added to a local Rock instance in order to test and/or the database against which it can be tested.
- [ ] Upload GIF(s) of relevant changes
- [X] Set a relevant reviewer

## REVIEW

- [ ] Review code through the lens of being concise, simple, and well-documented
- [ ] Manual QA to ensure the changes look/behave as expected

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@briankalwat What's the word with this PR? Is this something we're going to use?

**Comment by briankalwat** [comment]
@richarddubay yes, we just will need to update the attribute matrix templates whenever it gets deployed.

**Comment by richarddubay** [comment]
Okay, I'll take a look at this. It has that "do not merge" label on it so I didn't want to mess with it if I shouldn't. 👍

**Comment by richarddubay** [comment]
A couple questions:
1. I shouldn't technically really see any differences, right? If one is just replacing the other, they should look similar?
2. We're hardcoding `guids`? That doesn't seem like a good idea. I mean, hardcoding in general isn't a great idea. Do we have to hardcode these values? Is the speed improvement worth it? The answer might be "yes", but if we have to hardcode stuff then I'd question that. Like I am. 😂

**Comment by briankalwat** [comment]
@richarddubay the biggest change you'll see in the resulting feed is that audio/video feeds will now actually use the communicator data for podcasts - whereas before it was just the editorial feeds using it.

Hard-coding the guid of those attributes is really the safest thing we can do there, as the attribute keys and what not can all be changed from Rock. The guid, once it is created, will never be changed. That's why I used it.

This lava template will actually be able to be updated again once we have the persisted datasets for channels created. But one thing at a time. 😉

**Comment by richarddubay** [comment]
To test this, I changed out the code that was in the FEED lava short code and instead pointed it to the `feed.lava` file. 

A couple things I noticed:

1. The `<link>` on an item has a space in it after `https://newspring.cc`.
```
<link>
    https://newspring.cc /sermons/the-life-giving-church/a-church-that-invests-in-the-next-generation
</link>
```

You can see that here: https://rich.newspring.cc/GetChannelFeed.ashx?Count=100&ChannelId=19&TemplateId=1058

2. I added an author to the Tighten the Knot Toolkit article (https://rich.newspring.cc/articles/tighten-the-knot-toolkit) and I am not seeing it in the feed for that item.
https://rich.newspring.cc/GetChannelFeed.ashx?Count=100&ChannelId=16&TemplateId=523
```
<item>
    <title>
        <![CDATA[ Tighten The Knot Toolkit ]]>
    </title>
    <link>
        https://newspring.cc /articles/tighten-the-knot-toolkit
    </link>
    <pubDate>Sat, 07 Mar 2020 17:29:00 EST</pubDate>
    <category>Articles</category>
    <description>
        <![CDATA[<p>One thing you learned at Tighten The Knot marriage conference is that it takes more than a day to build a life. </p> <p>Marriages are made, one decision, one moment at a time. The tools below have been curated to equip you for every season of marriage. Empty-nester? Just getting started? It’s never too late to build something great.<br></p> <h3>Take a Next Step</h3> <ul> <li>Find support and encouragement in a <a href="http://www.newspring.cc/groups" target="_blank">NewSpring Group</a>. Use <a href="https://newspring.cc/workflows/81" target="_blank">this form</a> to join a group near you.</li> <li>Invite others to pray for you. The altar is a place of healing, not a place of pity. If you’re struggling, come borrow someone else’s faith. Take to your campus <a href="https://newspring.cc/care" target="_blank">Care Team</a> and let them pray with you and for you. </li> <li>Marriage counseling is a great way to break old patterns of thinking and believing. If you need help finding a counselor, your campus <a href="https://newspring.cc/care" target="_blank">Care Team</a> can help. </li> </ul> <h3>Read the Bible Together</h3> <p>Use <a href="https://newspring.cc/devotionals/tigthen-the-knot-a-14-day-devotional/" target="_blank">this study</a> to understand what the Bible says about marriage and navigate those tricky conversations every married couple faces — from how to love each other when you disagree, to what it means to put your spouse before your kids or extended family. <br></p> <h3>Learn More about God’s Design for Marriage</h3> <h5>NewSpring articles</h5> <ul> <li><a href="https://newspring.cc/articles/5-steps-to-take-your-marriage-from-good-to-great" target="_blank">Five steps to take your marriage from good to great</a></li> <li><a href="https://newspring.cc/articles/3-ways-to-show-grace-to-your-spouse" target="_blank">Three ways to show grace to your spouse</a></li> </ul> <h5>NewSpring Sermons </h5> <p>For all the reasons to break the knot, there's always a reason to tighten it. NewSpring did a six-week <a href="https://newspring.cc/sermons/tighten-the-knot" target="_blank">“Tighten The Knot” sermon series</a> in 2018 that address all the ways </p> <h5><span style="color: inherit; font-family: inherit;">Podcast recommendations</span><br></h5> <p><a href="https://podcasts.apple.com/us/podcast/marriagetoday-audio-podcast/id209659095" target="_blank">MarriageToday</a> - Hosted by best-selling author and speaker Jimmy Evans, MarriageToday is a daily program that provides hope and help for marriage and family relationships.<br></p> <p><a href="https://familyteams.com/podcasts/" target="_blank">Five Minute Fatherhood</a> - In this a five-minute weekday podcast Jeremy Pryor and Jeff Bethke share practical and tactical tips to equip fathers on their journey. <br></p> <p><a href="https://podcasts.apple.com/us/podcast/fight-hustle-end-hurry/id1480300467" target="_blank">Fight Hustle, End Hurry</a> - Listen as Jeff Bethke and author and pastor John Mark Comer discuss hustle and hurry, how they harm our spiritual lives, and what we can do about them. <br></p> <h5>Book recommendations</h5> <p>“<a href="https://www.amazon.com/Power-Praying%C2%AE-Wife-Stormie-Omartian/dp/0736957499?ref_=ast_slp_dp" target="_blank">The Power of a Praying Wife</a>” by Stormie Omartian<br>Learn how God can strengthen your marriage as you pray for key areas in your husband’s life. Be encouraged by Stormie's experiences, sample prayers, and related Bible verses.</p> <p>“<a href="https://www.amazon.com/Power-Praying%C2%AE-Husband-Stormie-Omartian/dp/0736957588/ref=sr_1_1?keywords=power+of+a+praying+husband&qid=1582735973&s=books&sr=1-1" target="_blank">The Power of a Praying Husband</a>” by Stormie Omartian<br>Packed with real-life examples and refreshing honesty, Stormie encourages husbands to intercede in every area of their wives’ lives.</p> <p>“<a href="https://www.amazon.com/Total-Forgiveness-R-T-Kendall/dp/1599791765/ref=sr_1_1?keywords=total+forgiveness&qid=1582736050&s=books&sr=1-1" target="_blank">Total Forgiveness</a>” by R.T. Kendall <br>One of the core messages of the gospel is that of total forgiveness — not only that we can be totally forgiven by God, but also that we must, in turn, totally forgive others.</p> <p>“<a href="https://www.amazon.com/Meaning-Marriage-Facing-Complexities-Commitment/dp/1594631875/ref=sr_1_1?crid=203OGBNJ18P4V&keywords=the+meaning+of+marriage+tim+keller&qid=1582735633&sprefix=the+meaning+of%2Caps%2C185&sr=8-1" target="_blank">The Meaning of Marriage</a>” by Timothy and Kathy Keller<br>This book shows everyone — Christians, skeptics, singles, married couples, and those about to be engaged — the Bible’s vision of marriage. You’ll learn how to have a successful marriage as well as how to know God and love Him and others more deeply.</p> <p>“<a href="https://www.amazon.com/Sacred-Marriage-What-Designed-Happy/dp/0310337372/ref=sr_1_1?crid=GQGYK5G2V4NP&keywords=sacred+marriage+by+gary+thomas&qid=1582735917&s=books&sprefix=sacred+%2Cstripbooks%2C205&sr=1-1" target="_blank">Sacred Marriage</a>” by Gary Thomas<br>In this popular bestselling book, Gary Thomas uncovers how marriage can be the doorway to a closer walk with God and each other.</p> <h3>Keep Dating One Another</h3> <p>The text challenges are over, but your pursuit of your spouse is not. Use these date ideas to keep making memories together. <br></p> <p><img src="https://s3.amazonaws.com/ns.images/newspring/editorial/articles/10.dates.jpg" style="width: 800px;" alt="10.dates.jpg"></p> <p><br></p> <p><img src="https://s3.amazonaws.com/ns.images/newspring/editorial/articles/30.dates.jpg" style="width: 800px;" alt="30.dates.jpg"></p> <p><br></p> <p><img src="https://s3.amazonaws.com/ns.images/newspring/editorial/articles/50.dates.jpg" style="width: 800px;" alt="50.dates.jpg"><br></p> ]]>
    </description>
    <guid>17643c5f-0b4b-4cd7-bbc5-218ea1f38e9c</guid>
</item>
```

Maybe I'm doing something wrong?

**Comment by briankalwat** [comment]
When this gets deployed, we'll need to update the `Formatted Lava` values of both the `Communicators` and `Scriptures` attribute matrix templates with the following lava:

`{%- capture attributeValuesObject %}{% if AttributeMatrixItems != empty -%}{
    "Attributes": [{%- for attributeMatrixItem in AttributeMatrixItems -%}{
        {%- for itemAttribute in ItemAttributes -%}
            {% assign av = attributeMatrixItem | Attribute:itemAttribute.Key | Trim %}
            "{{ itemAttribute.Key }}": "{{ av }}"{% if forloop.last != true %},{% endif %}
        {%- endfor -%}
    }{% if forloop.last != true %},{% endif %}{%- endfor -%}]
}{% endif %}{%- endcapture -%}{{ attributeValuesObject | Trim }}`

**Pull request merged**
