### PR TITLE
Prayer Request API Refactor

### PR DESCRIPTION
**Pull request by richarddubay**
Refactored the prayer request API endpoint to use less database calls. Renamed it per Spark's recommendation.

### CODE REVIEW

**Comment by richarddubay** [comment]
@IsaacHardy I changed the name of the API endpoint per Spark's recommendation. We'll have to change our Apollos Project to match it.

**Comment by redreceipt** [comment]
@richarddubay how do I test this?

**Comment by richarddubay** [comment]
@redreceipt If you have a Rock dev environment that works, you can pull down this branch locally and run it, making sure that you have a prayer request for you and someone else in one of your groups (like your wife perhaps because she's part of your family group), and then test the endpoint in the docs to make sure it pulls the prayer request for your other person and not you. 

Otherwise, without a working environment, your best bet is to just read the code, see if you can tell what it's doing and then give it a 👍 because it all makes sense. 

You can technically test out what's on alpha right now and know that this basically does the same thing, just in less calls and with a few tweaks. 😄

**Comment by redreceipt** [comment]
@richarddubay getting some internal error on build

Screen Shot 2019-03-24 at 1 57 22 PM

**Comment by IsaacHardy** [comment]
@cdanwards I will not be able to review this, could you review this for @richarddubay ?

**Comment by cdanwards** [comment]
@IsaacHardy I'm currently testing this PR but ran into some issues with my dev environment, so I'm just waiting for a reply from Paul, then I should be able to finish testing it.

**Pull request merged**
