### PR TITLE
Added billing address label

### PR DESCRIPTION
**Pull request by JakeDawkins**
For https://newspring.atlassian.net/browse/SYS-2453

# Context
There is a bug with displaying the credit card address when paying for an Event Registration.

# Goal
Show credit card billing address when signing up for an event

# Strategy
Added label field to the layout file

### CODE REVIEW

**Comment by dcs619** [comment]
@JakeDawkins Can you do PR's off of alpha?  This has too many merge commits

**Comment by JakeDawkins** [comment]
@dcs619 Yep!

**Comment by dcs619** [comment]
@JakeDawkins The commit history is coming from `fix-event-signup`.  Do you mind recreating that or rebasing it to alpha so the commit history for this PR is clean?

**Comment by dcs619** [comment]
@JakeDawkins I squashed the commits for this time.  In the future creating your branch from alpha makes for a clean tree.  This ensures that deploys to production can be quickly documented and tested.

**Comment by JakeDawkins** [comment]
@dcs619 👍

**Pull request merged**
