### PR TITLE
Updated related items swiper to remove legacy lava used for item summary attribute

### PR DESCRIPTION
**Pull request by briankalwat**

### CODE REVIEW

**Comment by redreceipt** [comment]
What am I testing here?

**Comment by richarddubay** [comment]
@briankalwat Just looking at this, I'm really unsure how these two things are really any different. In the old one you're pulling `item.Summary`. In the new one you're pulling summary off the item and then just using that. But that's not happening for other things that use the item dot notation ... `item.Content` for example. 

This is probably just my ignorance but which part is the "legacy" part?

**Comment by briankalwat** [comment]
@richarddubay @redreceipt dot notation in lava is used for properties of an object, whereas pipe notation is used for attributes. Legacy lava used to support attributes via dot notation, but there are severe performances losses from enabling legacy support - so hence we are trying to update all legacy lava so we can disable support for it and benefit from the performance gains.

**Comment by redreceipt** [comment]
so what's the intended outcome of this PR and i'll test it

**Comment by briankalwat** [comment]
@redreceipt the intended outcome is that you would be able to load any page that uses the `related-items-swiper` shortcode (anything editorial - articles, news, stories, etc) `https://michael-new.newspring.cc/articles/everything-you-need-to-know-about-acts` and **not** have an exception be logged.

**Pull request merged**
