### PR TITLE
Added PersonId

### PR DESCRIPTION
**Pull request by richarddubay**
+ Added the PersonId to the PrayerRequest/GetForGroupMembersOfPersonInGroupTypes API endpoint.

The URL should now look something like this:

`api/PrayerRequests/GetForGroupMembersOfPersonInGroupTypes/{personId}?excludePerson={true/false}&groupTypeIds={List of Ids}`

For example:

`api/PrayerRequests/GetForGroupMembersOfPersonInGroupTypes/158648?excludePerson=true&groupTypeIds=10,23,25`

### CODE REVIEW

**Comment by redreceipt** [comment]
@richarddubay Do I test this the same as the time? Is there something different I need to do to confirm the new functionality?

**Comment by richarddubay** [comment]
@redreceipt Yeah, you can test it in the API Docs like before. I'd also test the URL using something like Postman to make sure we can hit it.

**Comment by redreceipt** [comment]
curl ;)

**Comment by richarddubay** [comment]
Haha ... yeah. I always forget about Curl.

**Comment by redreceipt** [comment]
@richarddubay what would be the easiest way for me to get my auth header for a `curl` command?

**Pull request merged**
