### PR TITLE
[Alpha] Removed random 's' from using COMMAND S IN WINDOWS.

### PR DESCRIPTION
**Pull request by briankalwat**

### CODE REVIEW

**Comment by briankalwat** [comment]
@dcs619 you know this is funny….

**Comment by briankalwat** [comment]
@dcs619 do we need to clear cache on alpha for this to be visible?

**Comment by dcs619** [comment]
@briankalwat github pooped itself on the build https://ci.appveyor.com/project/NewSpring/rock/build/1.3.609

**Comment by briankalwat** [comment]
@dcs619 so I should create a new PR?

**Comment by dcs619** [comment]
No, I restarted the build.  Once it finishes it will auto-deploy

**Pull request merged**
